"""
Master company universe: 349 services businesses (US + UK).
Generated from expanded_services_universe_us_uk.xlsx.
Dict key = Yahoo Finance ticker (LSE stocks have .L suffix).
"""


COMPANY_REGISTRY: dict[str, dict] = {
    "GTLY.L": {
        "name": "Gateley (Holdings) plc",
        "sector": "consulting",
        "sub_sector": "legal_professional_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "CPI.L": {
        "name": "Capita plc",
        "sector": "consulting",
        "sub_sector": "outsourcing_public_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "XPS.L": {
        "name": "XPS Pensions Group plc",
        "sector": "consulting",
        "sub_sector": "pensions_consulting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "FDM.L": {
        "name": "FDM Group (Holdings) plc",
        "sector": "consulting",
        "sub_sector": "professional_services_training",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "BEG.L": {
        "name": "Begbies Traynor Group plc",
        "sector": "consulting",
        "sub_sector": "restructuring_advisory",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "FRP.L": {
        "name": "FRP Advisory Group plc",
        "sector": "consulting",
        "sub_sector": "restructuring_advisory",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "HAYS.L": {
        "name": "Hays plc",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "PAGE.L": {
        "name": "PageGroup plc",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RWA.L": {
        "name": "Robert Walters plc",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "STEM.L": {
        "name": "SThree plc",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "MMS": {
        "name": "Maximus, Inc.",
        "sector": "consulting",
        "sub_sector": "business_process_public_sector_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "RGP": {
        "name": "Resources Connection, Inc.",
        "sector": "consulting",
        "sub_sector": "business_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "KFY": {
        "name": "Korn Ferry",
        "sector": "consulting",
        "sub_sector": "hr_consulting_executive_search",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NSP": {
        "name": "Insperity, Inc.",
        "sector": "consulting",
        "sub_sector": "hr_outsourcing_peo",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "TNET": {
        "name": "TriNet Group, Inc.",
        "sector": "consulting",
        "sub_sector": "hr_outsourcing_peo",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ASGN": {
        "name": "ASGN Incorporated",
        "sector": "consulting",
        "sub_sector": "it_professional_staffing",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BAH": {
        "name": "Booz Allen Hamilton Holding Corporation",
        "sector": "consulting",
        "sub_sector": "management_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CRAI": {
        "name": "CRA International, Inc.",
        "sector": "consulting",
        "sub_sector": "management_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "FCN": {
        "name": "FTI Consulting, Inc.",
        "sector": "consulting",
        "sub_sector": "management_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "HURN": {
        "name": "Huron Consulting Group Inc.",
        "sector": "consulting",
        "sub_sector": "management_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ICFI": {
        "name": "ICF International, Inc.",
        "sector": "consulting",
        "sub_sector": "management_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ADP": {
        "name": "Automatic Data Processing, Inc.",
        "sector": "consulting",
        "sub_sector": "payroll_hr_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "PAYX": {
        "name": "Paychex, Inc.",
        "sector": "consulting",
        "sub_sector": "payroll_hr_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CBZ": {
        "name": "CBIZ, Inc.",
        "sector": "consulting",
        "sub_sector": "professional_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FORR": {
        "name": "Forrester Research, Inc.",
        "sector": "consulting",
        "sub_sector": "research_advisory",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "BBSI": {
        "name": "Barrett Business Services, Inc.",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "KELYA": {
        "name": "Kelly Services, Inc.",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "KFRC": {
        "name": "Kforce Inc.",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MAN": {
        "name": "ManpowerGroup Inc.",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "RHI": {
        "name": "Robert Half Inc.",
        "sector": "consulting",
        "sub_sector": "staffing_recruiting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CSN.L": {
        "name": "Chesnara plc",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "JUST.L": {
        "name": "Just Group plc",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "LGEN.L": {
        "name": "Legal & General Group plc",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "PHNX.L": {
        "name": "Phoenix Group Holdings plc",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "PUK.L": {
        "name": "Prudential plc",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "HUW.L": {
        "name": "Helios Underwriting plc",
        "sector": "insurance",
        "sub_sector": "lloyd_s_underwriting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "AV.L": {
        "name": "Aviva plc",
        "sector": "insurance",
        "sub_sector": "multi_line_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "ADM.L": {
        "name": "Admiral Group plc",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "DLG.L": {
        "name": "Direct Line Insurance Group plc",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SBRE.L": {
        "name": "Sabre Insurance Group plc",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "BEZ.L": {
        "name": "Beazley plc",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "HSX.L": {
        "name": "Hiscox Ltd",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "LRE.L": {
        "name": "Lancashire Holdings Limited",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "CRD.A": {
        "name": "Crawford & Company",
        "sector": "insurance",
        "sub_sector": "claims_tpa",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CRD.B": {
        "name": "Crawford & Company",
        "sector": "insurance",
        "sub_sector": "claims_tpa",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CRVL": {
        "name": "CorVel Corporation",
        "sector": "insurance",
        "sub_sector": "claims_tpa",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CI": {
        "name": "The Cigna Group",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CNC": {
        "name": "Centene Corporation",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ELV": {
        "name": "Elevance Health, Inc.",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "HUM": {
        "name": "Humana Inc.",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MOH": {
        "name": "Molina Healthcare, Inc.",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "OSCR": {
        "name": "Oscar Health, Inc.",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "UNH": {
        "name": "UnitedHealth Group Incorporated",
        "sector": "insurance",
        "sub_sector": "health_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AJG": {
        "name": "Arthur J. Gallagher & Co.",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AON": {
        "name": "Aon plc",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BRO": {
        "name": "Brown & Brown, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BRP": {
        "name": "BRP Group, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ERIE": {
        "name": "Erie Indemnity Company",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "MMC": {
        "name": "Marsh & McLennan Companies, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "RYAN": {
        "name": "Ryan Specialty Holdings, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "WTW": {
        "name": "Willis Towers Watson Public Limited Company",
        "sector": "insurance",
        "sub_sector": "insurance_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "EHTH": {
        "name": "eHealth, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_distribution",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "GOCO": {
        "name": "GoHealth, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_distribution",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "GSHD": {
        "name": "Goosehead Insurance, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_distribution",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "SLQT": {
        "name": "SelectQuote, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_distribution",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "TWFG": {
        "name": "TWFG, Inc.",
        "sector": "insurance",
        "sub_sector": "insurance_distribution",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "HIPO": {
        "name": "Hippo Holdings Inc.",
        "sector": "insurance",
        "sub_sector": "insurtech",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "LMND": {
        "name": "Lemonade, Inc.",
        "sector": "insurance",
        "sub_sector": "insurtech",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ROOT": {
        "name": "Root, Inc.",
        "sector": "insurance",
        "sub_sector": "insurtech",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "AFL": {
        "name": "Aflac Incorporated",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BHF": {
        "name": "Brighthouse Financial, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CNO": {
        "name": "CNO Financial Group, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FG": {
        "name": "F&G Annuities & Life, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "GL": {
        "name": "Globe Life Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "LNC": {
        "name": "Lincoln National Corporation",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MET": {
        "name": "MetLife, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MFC": {
        "name": "Manulife Financial Corporation",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PFG": {
        "name": "Principal Financial Group, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "PRU": {
        "name": "Prudential Financial, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "SLF": {
        "name": "Sun Life Financial Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "UNM": {
        "name": "Unum Group",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "VOYA": {
        "name": "Voya Financial, Inc.",
        "sector": "insurance",
        "sub_sector": "life_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ESNT": {
        "name": "Essent Group Ltd.",
        "sector": "insurance",
        "sub_sector": "mortgage_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MTG": {
        "name": "MGIC Investment Corporation",
        "sector": "insurance",
        "sub_sector": "mortgage_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NMIH": {
        "name": "NMI Holdings, Inc.",
        "sector": "insurance",
        "sub_sector": "mortgage_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "RDN": {
        "name": "Radian Group Inc.",
        "sector": "insurance",
        "sub_sector": "mortgage_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AFG": {
        "name": "American Financial Group, Inc.",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AIG": {
        "name": "American International Group, Inc.",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ALL": {
        "name": "The Allstate Corporation",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CB": {
        "name": "Chubb Limited",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CINF": {
        "name": "Cincinnati Financial Corporation",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "HIG": {
        "name": "The Hartford Financial Services Group, Inc.",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MKL": {
        "name": "Markel Group Inc.",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PGR": {
        "name": "The Progressive Corporation",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "TRV": {
        "name": "The Travelers Companies, Inc.",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "WRB": {
        "name": "W. R. Berkley Corporation",
        "sector": "insurance",
        "sub_sector": "p_c_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AXS": {
        "name": "AXIS Capital Holdings Limited",
        "sector": "insurance",
        "sub_sector": "reinsurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EG": {
        "name": "Everest Group, Ltd.",
        "sector": "insurance",
        "sub_sector": "reinsurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "RNR": {
        "name": "RenaissanceRe Holdings Ltd.",
        "sector": "insurance",
        "sub_sector": "reinsurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ACGL": {
        "name": "Arch Capital Group Ltd.",
        "sector": "insurance",
        "sub_sector": "reinsurance_specialty",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "AIZ": {
        "name": "Assurant, Inc.",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "KNSL": {
        "name": "Kinsale Capital Group, Inc.",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ORI": {
        "name": "Old Republic International Corporation",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "RLI": {
        "name": "RLI Corp.",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "SIGI": {
        "name": "Selective Insurance Group, Inc.",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "SKWD": {
        "name": "Skyward Specialty Insurance Group, Inc.",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TRUP": {
        "name": "Trupanion, Inc.",
        "sector": "insurance",
        "sub_sector": "specialty_insurance",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "FAF": {
        "name": "Fidelity National Financial, Inc.",
        "sector": "insurance",
        "sub_sector": "title_insurance",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "INF.L": {
        "name": "Informa plc",
        "sector": "info_data",
        "sub_sector": "b2b_information_events_publishing",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "WIL.L": {
        "name": "Wilmington plc",
        "sector": "info_data",
        "sub_sector": "compliance_professional_information",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "EXPN.L": {
        "name": "Experian plc",
        "sector": "info_data",
        "sub_sector": "credit_consumer_data",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "LSEG.L": {
        "name": "London Stock Exchange Group plc",
        "sector": "info_data",
        "sub_sector": "financial_data_benchmark_administration",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "GBG.L": {
        "name": "GB Group plc",
        "sector": "info_data",
        "sub_sector": "identity_fraud_data",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "DATA.L": {
        "name": "GlobalData Plc",
        "sector": "info_data",
        "sub_sector": "industry_data_market_intelligence",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "YOU.L": {
        "name": "YouGov plc",
        "sector": "info_data",
        "sub_sector": "public_opinion_data_analytics",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "REL.L": {
        "name": "RELX PLC",
        "sector": "info_data",
        "sub_sector": "scientific_legal_information",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "DNB": {
        "name": "Dun & Bradstreet Holdings, Inc.",
        "sector": "info_data",
        "sub_sector": "business_information",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EFX": {
        "name": "Equifax Inc.",
        "sector": "info_data",
        "sub_sector": "credit_identity_data",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "TRU": {
        "name": "TransUnion",
        "sector": "info_data",
        "sub_sector": "credit_data_scores",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MCO": {
        "name": "Moody\'s Corporation",
        "sector": "info_data",
        "sub_sector": "credit_ratings_analytics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CBOE": {
        "name": "Cboe Global Markets, Inc.",
        "sector": "info_data",
        "sub_sector": "exchange_market_data",
        "exchange": "Cboe BZX",
        "listing_country": "US",
    },
    "FDS": {
        "name": "FactSet Research Systems Inc.",
        "sector": "info_data",
        "sub_sector": "financial_data",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "SPGI": {
        "name": "S&P Global Inc.",
        "sector": "info_data",
        "sub_sector": "financial_data_analytics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CLVT": {
        "name": "Clarivate Plc",
        "sector": "info_data",
        "sub_sector": "ip_academic_enterprise_information",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MSCI": {
        "name": "MSCI Inc.",
        "sector": "info_data",
        "sub_sector": "index_analytics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MORN": {
        "name": "Morningstar, Inc.",
        "sector": "info_data",
        "sub_sector": "investment_data",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TRI": {
        "name": "Thomson Reuters Corporation",
        "sector": "info_data",
        "sub_sector": "legal_tax_regulatory_information",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MKTW": {
        "name": "MarketWise, Inc.",
        "sector": "info_data",
        "sub_sector": "market_intelligence",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CSGP": {
        "name": "CoStar Group, Inc.",
        "sector": "info_data",
        "sub_sector": "property_real_estate_data",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "VRSK": {
        "name": "Verisk Analytics, Inc.",
        "sector": "info_data",
        "sub_sector": "risk_insurance_data",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "RELX": {
        "name": "RELX PLC",
        "sector": "info_data",
        "sub_sector": "scientific_legal_information",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CME": {
        "name": "CME Group Inc.",
        "sector": "info_data",
        "sub_sector": "stock_exchange_market_data",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ICE": {
        "name": "Intercontinental Exchange, Inc.",
        "sector": "info_data",
        "sub_sector": "stock_exchange_market_data",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NDAQ": {
        "name": "Nasdaq, Inc.",
        "sector": "info_data",
        "sub_sector": "stock_exchange_market_data",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "VALU": {
        "name": "Value Line, Inc.",
        "sector": "info_data",
        "sub_sector": "valuation_workflow_data",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "NCC.L": {
        "name": "NCC Group plc",
        "sector": "it_services",
        "sub_sector": "cybersecurity_it_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "KNOS.L": {
        "name": "Kainos Group plc",
        "sector": "it_services",
        "sub_sector": "digital_services_software_engineering",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "BYIT.L": {
        "name": "Bytes Technology Group plc",
        "sector": "it_services",
        "sub_sector": "it_reseller_solutions",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "CCC.L": {
        "name": "Computacenter plc",
        "sector": "it_services",
        "sub_sector": "it_reseller_solutions",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SCT.L": {
        "name": "Softcat plc",
        "sector": "it_services",
        "sub_sector": "it_reseller_solutions",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RCN.L": {
        "name": "Redcentric plc",
        "sector": "it_services",
        "sub_sector": "managed_network_cloud_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "EXLS": {
        "name": "ExlService Holdings, Inc.",
        "sector": "it_services",
        "sub_sector": "analytics_digital_ops",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CNXC": {
        "name": "Concentrix Corporation",
        "sector": "it_services",
        "sub_sector": "business_process_outsourcing",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TASK": {
        "name": "TaskUs, Inc.",
        "sector": "it_services",
        "sub_sector": "customer_experience_outsourcing",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "IBEX": {
        "name": "IBEX Limited",
        "sector": "it_services",
        "sub_sector": "customer_experience_bpo",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TTEC": {
        "name": "TTEC Holdings, Inc.",
        "sector": "it_services",
        "sub_sector": "customer_experience_bpo",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "G": {
        "name": "Genpact Limited",
        "sector": "it_services",
        "sub_sector": "digital_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "GLOB": {
        "name": "Globant S.A.",
        "sector": "it_services",
        "sub_sector": "digital_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "DAVA": {
        "name": "Endava plc",
        "sector": "it_services",
        "sub_sector": "digital_engineering",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EPAM": {
        "name": "EPAM Systems, Inc.",
        "sector": "it_services",
        "sub_sector": "digital_engineering",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "GDYN": {
        "name": "Grid Dynamics Holdings, Inc.",
        "sector": "it_services",
        "sub_sector": "digital_engineering",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TWKS": {
        "name": "Thoughtworks Holding, Inc.",
        "sector": "it_services",
        "sub_sector": "digital_engineering",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "PSN": {
        "name": "Parsons Corporation",
        "sector": "it_services",
        "sub_sector": "digital_transformation_engineering",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "VYX": {
        "name": "NCR Voyix Corporation",
        "sector": "it_services",
        "sub_sector": "enterprise_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BR": {
        "name": "Broadridge Financial Solutions, Inc.",
        "sector": "it_services",
        "sub_sector": "fintech_investor_communications_tech",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CACI": {
        "name": "CACI International Inc",
        "sector": "it_services",
        "sub_sector": "government_it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "LDOS": {
        "name": "Leidos Holdings, Inc.",
        "sector": "it_services",
        "sub_sector": "government_it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "SAIC": {
        "name": "Science Applications International Corporation",
        "sector": "it_services",
        "sub_sector": "government_it_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ACN": {
        "name": "Accenture plc",
        "sector": "it_services",
        "sub_sector": "it_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PLUS": {
        "name": "ePlus inc.",
        "sector": "it_services",
        "sub_sector": "it_reseller_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CDW": {
        "name": "CDW Corporation",
        "sector": "it_services",
        "sub_sector": "it_reseller_solutions",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CTSH": {
        "name": "Cognizant Technology Solutions Corporation",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "DXC": {
        "name": "DXC Technology Company",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FIS": {
        "name": "Fidelity National Information Services, Inc.",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "GIB": {
        "name": "CGI Inc.",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "IBM": {
        "name": "International Business Machines Corporation",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "INFY": {
        "name": "Infosys Limited",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "UIS": {
        "name": "Unisys Corporation",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "WIT": {
        "name": "Wipro Limited",
        "sector": "it_services",
        "sub_sector": "it_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NSIT": {
        "name": "Insight Enterprises, Inc.",
        "sector": "it_services",
        "sub_sector": "it_solutions_reseller",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "NIQ": {
        "name": "NIQ Global Intelligence plc",
        "sector": "it_services",
        "sub_sector": "information_services_analytics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NABL": {
        "name": "N-able, Inc.",
        "sector": "it_services",
        "sub_sector": "msp_software_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "KD": {
        "name": "Kyndryl Holdings, Inc.",
        "sector": "it_services",
        "sub_sector": "managed_infrastructure",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "JKHY": {
        "name": "Jack Henry & Associates, Inc.",
        "sector": "it_services",
        "sub_sector": "payments_financial_software_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "IT": {
        "name": "Gartner, Inc.",
        "sector": "it_services",
        "sub_sector": "research_advisory",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "IHP.L": {
        "name": "IntegraFin Holdings plc",
        "sector": "wealth_mgmt",
        "sub_sector": "platform_adviser_admin",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "ABDN.L": {
        "name": "abrdn plc",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "JUP.L": {
        "name": "Jupiter Fund Management plc",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "LIO.L": {
        "name": "Liontrust Asset Management plc",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "POLR.L": {
        "name": "Polar Capital Holdings plc",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SDR.L": {
        "name": "Schroders plc",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "JTC.L": {
        "name": "JTC PLC",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_fiduciary_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "AJB.L": {
        "name": "AJ Bell plc",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "BRK.L": {
        "name": "Brooks Macdonald Group plc",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "QLT.L": {
        "name": "Quilter plc",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RAT.L": {
        "name": "Rathbones Group Plc",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "STJ.L": {
        "name": "St. James\'s Place plc",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "TAM.L": {
        "name": "Tatton Asset Management plc",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "EVR": {
        "name": "Evercore Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "advisory_investment_banking",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "HLI": {
        "name": "Houlihan Lokey, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "advisory_investment_banking",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "LAZ": {
        "name": "Lazard, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "advisory_investment_banking",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MC": {
        "name": "Moelis & Company",
        "sector": "wealth_mgmt",
        "sub_sector": "advisory_investment_banking",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PJT": {
        "name": "PJT Partners Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "advisory_investment_banking",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "WT": {
        "name": "WisdomTree, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "etf_digital_wealth",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AAMI": {
        "name": "Acadian Asset Management Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AMG": {
        "name": "Affiliated Managers Group, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "APAM": {
        "name": "Artisan Partners Asset Management Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BEN": {
        "name": "Franklin Resources, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BLK": {
        "name": "BlackRock, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CNS": {
        "name": "Cohen & Steers, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FHI": {
        "name": "Federated Hermes, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "JHG": {
        "name": "Janus Henderson Group plc",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "TROW": {
        "name": "T. Rowe Price Group, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "VCTR": {
        "name": "Victory Capital Holdings, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "traditional_asset_management",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "SEIC": {
        "name": "SEI Investments Company",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_adviser_platform",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "AMP": {
        "name": "Ameriprise Financial, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "LPLA": {
        "name": "LPL Financial Holdings Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "RJF": {
        "name": "Raymond James Financial, Inc.",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "SF": {
        "name": "Stifel Financial Corp.",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PIPR": {
        "name": "Piper Sandler Companies",
        "sector": "wealth_mgmt",
        "sub_sector": "wealth_management_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BNZL.L": {
        "name": "Bunzl plc",
        "sector": "supply_chain",
        "sub_sector": "distribution_outsourcing",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RS1.L": {
        "name": "RS Group plc",
        "sector": "supply_chain",
        "sub_sector": "industrial_mro_distribution",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "DPLM.L": {
        "name": "Diploma PLC",
        "sector": "supply_chain",
        "sub_sector": "specialized_distribution",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "CHRW": {
        "name": "C.H. Robinson Worldwide, Inc.",
        "sector": "supply_chain",
        "sub_sector": "3pl_freight_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "FWRD": {
        "name": "Forward Air Corporation",
        "sector": "supply_chain",
        "sub_sector": "air_freight_forwarding",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "LSTR": {
        "name": "Landstar System, Inc.",
        "sector": "supply_chain",
        "sub_sector": "asset_light_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "RLGT": {
        "name": "Radiant Logistics, Inc.",
        "sector": "supply_chain",
        "sub_sector": "asset_light_logistics",
        "exchange": "NYSE American",
        "listing_country": "US",
    },
    "RXO": {
        "name": "RXO, Inc.",
        "sector": "supply_chain",
        "sub_sector": "asset_light_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ULH": {
        "name": "Universal Logistics Holdings, Inc.",
        "sector": "supply_chain",
        "sub_sector": "asset_light_trucking_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "GXO": {
        "name": "GXO Logistics, Inc.",
        "sector": "supply_chain",
        "sub_sector": "contract_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EXPD": {
        "name": "Expeditors International of Washington, Inc.",
        "sector": "supply_chain",
        "sub_sector": "freight_forwarding",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FERG": {
        "name": "Ferguson Enterprises Inc.",
        "sector": "supply_chain",
        "sub_sector": "industrial_distribution_supply_chain",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FDX": {
        "name": "FedEx Corporation",
        "sector": "supply_chain",
        "sub_sector": "integrated_freight_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "UPS": {
        "name": "United Parcel Service, Inc.",
        "sector": "supply_chain",
        "sub_sector": "integrated_freight_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "HUBG": {
        "name": "Hub Group, Inc.",
        "sector": "supply_chain",
        "sub_sector": "intermodal_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ARCB": {
        "name": "ArcBest Corporation",
        "sector": "supply_chain",
        "sub_sector": "ltl_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ODFL": {
        "name": "Old Dominion Freight Line, Inc.",
        "sector": "supply_chain",
        "sub_sector": "ltl_transportation",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "SAIA": {
        "name": "Saia, Inc.",
        "sector": "supply_chain",
        "sub_sector": "ltl_transportation",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "PBI": {
        "name": "Pitney Bowes Inc.",
        "sector": "supply_chain",
        "sub_sector": "mail_shipping_solutions",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "JBHT": {
        "name": "J.B. Hunt Transport Services, Inc.",
        "sector": "supply_chain",
        "sub_sector": "transportation_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "XPO": {
        "name": "XPO, Inc.",
        "sector": "supply_chain",
        "sub_sector": "transportation_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CVLG": {
        "name": "Covenant Logistics Group, Inc.",
        "sector": "supply_chain",
        "sub_sector": "truckload_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "KNX": {
        "name": "Knight-Swift Transportation Holdings Inc.",
        "sector": "supply_chain",
        "sub_sector": "truckload_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "MRTN": {
        "name": "Marten Transport, Ltd.",
        "sector": "supply_chain",
        "sub_sector": "truckload_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "SNDR": {
        "name": "Schneider National, Inc.",
        "sector": "supply_chain",
        "sub_sector": "truckload_logistics",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "WERN": {
        "name": "Werner Enterprises, Inc.",
        "sector": "supply_chain",
        "sub_sector": "truckload_logistics",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "COST.L": {
        "name": "Costain Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "construction_engineering",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RCDO.L": {
        "name": "Ricardo plc",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "BAB.L": {
        "name": "Babcock International Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "KLR.L": {
        "name": "Keller Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RNWH.L": {
        "name": "Renew Holdings plc",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "WG.L": {
        "name": "John Wood Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "MTO.L": {
        "name": "Mitie Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "facilities_field_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "MER.L": {
        "name": "Mears Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "field_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SRP.L": {
        "name": "Serco Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "government_field_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SFR.L": {
        "name": "Severfield plc",
        "sector": "field_eng_tic",
        "sub_sector": "steel_construction_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "ITRK.L": {
        "name": "Intertek Group plc",
        "sector": "field_eng_tic",
        "sub_sector": "testing_inspection_certification",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "BLD": {
        "name": "TopBuild Corp.",
        "sector": "field_eng_tic",
        "sub_sector": "building_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "GVA": {
        "name": "Granite Construction Incorporated",
        "sector": "field_eng_tic",
        "sub_sector": "civil_engineering",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EME": {
        "name": "EMCOR Group, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "electrical_building_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "IESC": {
        "name": "IES Holdings, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "electrical_industrial_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "MYRG": {
        "name": "MYR Group Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "electrical_infrastructure_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ACM": {
        "name": "AECOM",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BWMN": {
        "name": "Bowman Consulting Group Ltd.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "J": {
        "name": "Jacobs Solutions Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NVEE": {
        "name": "NV5 Global, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "STN": {
        "name": "Stantec Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "TTEK": {
        "name": "Tetra Tech, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "FLR": {
        "name": "Fluor Corporation",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_epc",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "KBR": {
        "name": "KBR, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_government_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "AGX": {
        "name": "Argan, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_lifting_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "WLDN": {
        "name": "Willdan Group, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "engineering_power_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "MTRX": {
        "name": "Matrix Service Company",
        "sector": "field_eng_tic",
        "sub_sector": "industrial_energy_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "STRL": {
        "name": "Sterling Infrastructure, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "infrastructure_civil_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "MTZ": {
        "name": "MasTec, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "infrastructure_utility_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PRIM": {
        "name": "Primoris Services Corporation",
        "sector": "field_eng_tic",
        "sub_sector": "infrastructure_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PWR": {
        "name": "Quanta Services, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "infrastructure_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ROAD": {
        "name": "Construction Partners, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "infrastructure_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ORN": {
        "name": "Orion Group Holdings, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "marine_specialty_construction",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FIX": {
        "name": "Comfort Systems USA, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "mechanical_hvac_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "OII": {
        "name": "Oceaneering International, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "offshore_field_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "APG": {
        "name": "APi Group Corporation",
        "sector": "field_eng_tic",
        "sub_sector": "safety_fire_protection_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EXPO": {
        "name": "Exponent, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "scientific_engineering_consulting",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "DY": {
        "name": "Dycom Industries, Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "telecom_utility_field_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ULS": {
        "name": "UL Solutions Inc.",
        "sector": "field_eng_tic",
        "sub_sector": "testing_inspection_certification",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BLV.L": {
        "name": "Belvoir Group PLC",
        "sector": "property",
        "sub_sector": "estate_agency_lettings",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "TPFG.L": {
        "name": "The Property Franchise Group PLC",
        "sector": "property",
        "sub_sector": "estate_agency_franchising",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "RMV.L": {
        "name": "Rightmove plc",
        "sector": "property",
        "sub_sector": "property_portal",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "LSL.L": {
        "name": "LSL Property Services plc",
        "sector": "property",
        "sub_sector": "property_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SVS.L": {
        "name": "Savills plc",
        "sector": "property",
        "sub_sector": "real_estate_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "FOXT.L": {
        "name": "Foxtons Group plc",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "WINK.L": {
        "name": "M Winkworth plc",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "MMI": {
        "name": "Marcus & Millichap, Inc.",
        "sector": "property",
        "sub_sector": "commercial_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CIGI": {
        "name": "Colliers International Group Inc.",
        "sector": "property",
        "sub_sector": "commercial_real_estate_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CWK": {
        "name": "Cushman & Wakefield plc",
        "sector": "property",
        "sub_sector": "commercial_real_estate_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "NMRK": {
        "name": "Newmark Group, Inc.",
        "sector": "property",
        "sub_sector": "commercial_real_estate_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "OPAD": {
        "name": "Offerpad Solutions Inc.",
        "sector": "property",
        "sub_sector": "home_transaction_platform",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FSV": {
        "name": "FirstService Corporation",
        "sector": "property",
        "sub_sector": "property_management_residential_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ASPS": {
        "name": "Altisource Portfolio Solutions S.A.",
        "sector": "property",
        "sub_sector": "property_services_mortgage_tech",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "CBRE": {
        "name": "CBRE Group, Inc.",
        "sector": "property",
        "sub_sector": "real_estate_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "JLL": {
        "name": "Jones Lang LaSalle Incorporated",
        "sector": "property",
        "sub_sector": "real_estate_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "COMP": {
        "name": "Compass, Inc.",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "DOUG": {
        "name": "Douglas Elliman Inc.",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EXPI": {
        "name": "eXp World Holdings, Inc.",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "FTHM": {
        "name": "Fathom Holdings Inc.",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "REAX": {
        "name": "The Real Brokerage Inc.",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "RMAX": {
        "name": "RE/MAX Holdings, Inc.",
        "sector": "property",
        "sub_sector": "residential_brokerage",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BEKE": {
        "name": "KE Holdings Inc.",
        "sector": "property",
        "sub_sector": "residential_platform",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "OPEN": {
        "name": "Opendoor Technologies Inc.",
        "sector": "property",
        "sub_sector": "ibuying_residential_platform",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "PSON.L": {
        "name": "Pearson plc",
        "sector": "education",
        "sub_sector": "education_publishing",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "MLVN.L": {
        "name": "Malvern International plc",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "GHC": {
        "name": "Graham Holdings Company",
        "sector": "education",
        "sub_sector": "education_media",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "UTI": {
        "name": "Universal Technical Institute, Inc.",
        "sector": "education",
        "sub_sector": "education_training",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CHGG": {
        "name": "Chegg, Inc.",
        "sector": "education",
        "sub_sector": "education_platform",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "COUR": {
        "name": "Coursera, Inc.",
        "sector": "education",
        "sub_sector": "education_platform",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "UDMY": {
        "name": "Udemy, Inc.",
        "sector": "education",
        "sub_sector": "education_platform",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "AFYA": {
        "name": "Afya Limited",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "APEI": {
        "name": "American Public Education, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "ATGE": {
        "name": "Adtalem Global Education Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "DAO": {
        "name": "Youdao, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "EDU": {
        "name": "New Oriental Education & Technology Group Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "FC": {
        "name": "Franklin Covey Co.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "GOTU": {
        "name": "Gaotu Techedu Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "KLC": {
        "name": "Kindercare Learning Companies, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "LAUR": {
        "name": "Laureate Education, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "LINC": {
        "name": "Lincoln Educational Services Corporation",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "LOPE": {
        "name": "Grand Canyon Education, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "LRN": {
        "name": "Stride, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PRDO": {
        "name": "Perdoceo Education Corporation",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "STRA": {
        "name": "Strategic Education, Inc.",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TAL": {
        "name": "TAL Education Group",
        "sector": "education",
        "sub_sector": "education_services",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BPT.L": {
        "name": "Bridgepoint Group plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "EMG.L": {
        "name": "Man Group plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "ICG.L": {
        "name": "ICG plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "III.L": {
        "name": "3i Group plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "PHLL.L": {
        "name": "Petershill Partners plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "ASHM.L": {
        "name": "Ashmore Group PLC",
        "sector": "alt_asset_mgmt",
        "sub_sector": "emerging_markets_alternatives",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "FSG.L": {
        "name": "Foresight Group Holdings Limited",
        "sector": "alt_asset_mgmt",
        "sub_sector": "infrastructure_private_assets",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "HGT.L": {
        "name": "HgCapital Trust plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "private_equity_investment_company",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "HVPE.L": {
        "name": "HarbourVest Global Private Equity Limited",
        "sector": "alt_asset_mgmt",
        "sub_sector": "private_equity_investment_company",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "NBPE.L": {
        "name": "NB Private Equity Partners Limited",
        "sector": "alt_asset_mgmt",
        "sub_sector": "private_equity_investment_company",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "PNL.L": {
        "name": "Pantheon International Plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "private_equity_investment_company",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "IPO.L": {
        "name": "IP Group plc",
        "sector": "alt_asset_mgmt",
        "sub_sector": "venture_alternatives",
        "exchange": "LSE",
        "listing_country": "UK",
    },
    "SII": {
        "name": "Sprott Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_resource_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "APO": {
        "name": "Apollo Global Management, Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "ARES": {
        "name": "Ares Management Corporation",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BAM": {
        "name": "Brookfield Asset Management Ltd.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BN": {
        "name": "Brookfield Corporation",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "BX": {
        "name": "Blackstone Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "CG": {
        "name": "The Carlyle Group Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "GCMG": {
        "name": "GCM Grosvenor Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "HLNE": {
        "name": "Hamilton Lane Incorporated",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "KKR": {
        "name": "KKR & Co. Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "OWL": {
        "name": "Blue Owl Capital Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "P10": {
        "name": "P10, Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NYSE",
        "listing_country": "US",
    },
    "PAX": {
        "name": "Patria Investments Limited",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "STEP": {
        "name": "StepStone Group Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "TPG": {
        "name": "TPG Inc.",
        "sector": "alt_asset_mgmt",
        "sub_sector": "alternative_asset_manager",
        "exchange": "NASDAQ",
        "listing_country": "US",
    },
    "BUR": {
        "name": "Burford Capital Limited",
        "sector": "alt_asset_mgmt",
        "sub_sector": "litigation_finance_alternatives",
        "exchange": "NYSE",
        "listing_country": "US",
    },
}
